# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cuis Smalltalk
email: cuis-dev@cuis-smalltalk.org
description: > # this means to ignore newlines until "baseurl:"
  Cuis is an Open Source, multiplatform Smalltalk-80 system.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cuis-smalltalk.github.io" # the base hostname & protocol for your site
github_username:  "Cuis-Smalltalk"

# Build settings
#markdown: redcarpet
#redcarpet:
#  extensions:
#    - lax_spacing
#    - with_toc_data

# markdown: kramdown

# kramdown:
#   input: GFM

markdown: CommonMarkGhPages

plugins:
  - jekyll-relative-links

relative_links:
  enabled:     true
  collections: true

permalink: pretty

exclude:
  - Documentation
  - vendor/bundle
  - scripts
